version: 2

sources:

  - name: xero
    database: dwh_pwx_poc
    schema: xero
    tables:
      - name: invoice
        description: "invoice in xero"

      - name: item
        description: "item in xero"
